version: '3'
services:
  db:
    image: 'mongo'
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - db

networks:
  my_network:
    driver: bridge

volumes:
  mongodb_data:
  node_modules: 
  web-root: 
    driver: local

