apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cc-helm-chart.fullname" . }}-frontend
  labels:
    io.kompose.service: frontend
  {{- include "cc-helm-chart.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: C:\Users\Admin\AppData\Local\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      io.kompose.service: frontend
    {{- include "cc-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.service: frontend
      {{- include "cc-helm-chart.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: C:\Users\Admin\AppData\Local\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.frontend.frontend.image.repository }}:{{ .Values.frontend.frontend.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.frontend.frontend.imagePullPolicy }}
        name: frontend
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
      restartPolicy: Always