apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    io.kompose.service: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32001
  type: NodePort

