apiVersion: v1
kind: Service
metadata:
  name: backend2
spec:
  selector:
    io.kompose.service: backend2
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 32002
  type: NodePort 
