apiVersion: v1
kind: Service
metadata:
  name: {{ include "cc-helm-chart.fullname" . }}-backend2
  labels:
  {{- include "cc-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend2.type }}
  selector:
    io.kompose.service: backend2
  {{- include "cc-helm-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.backend2.ports | toYaml | nindent 2 }}