apiVersion: v1
kind: Service
metadata:
  name: {{ include "cc-helm-chart.fullname" . }}-frontend
  labels:
  {{- include "cc-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.type }}
  selector:
    io.kompose.service: frontend
  {{- include "cc-helm-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.frontend.ports | toYaml | nindent 2 }}